// packages/cli/src/commands/entries.ts
//
// Read-only CLI command for inspecting Entries generated by the perception
// worker. Phase 1a — regeneration is daemon-driven; a `regenerate` subcommand
// is deferred to Phase 1b where it shares logic with the enrichment pipeline.

import { parseEntryKey, type Entry } from "@claude-lens/entries";
import {
  listEntriesForDay,
  listEntriesForSession,
  listEntryKeys,
  readEntry,
} from "@claude-lens/entries/fs";
import { flag } from "../args.js";

export async function entries(args: string[]): Promise<void> {
  if (args.includes("--help") || args.includes("-h")) {
    printHelp();
    return;
  }

  const json = args.includes("--json");
  const dayArg = flag(args, "--day");
  const sessionArg = flag(args, "--session");
  const all = args.includes("--all");

  if (dayArg) {
    printEntries(listEntriesForDay(dayArg), json);
    return;
  }
  if (sessionArg) {
    printEntries(listEntriesForSession(sessionArg), json);
    return;
  }
  if (all) {
    const list: Entry[] = [];
    for (const key of listEntryKeys()) {
      const parsed = parseEntryKey(key);
      if (!parsed) continue;
      const e = readEntry(parsed.session_id, parsed.local_day);
      if (e) list.push(e);
    }
    printEntries(list, json);
    return;
  }

  // Default: summary counts.
  const keys = listEntryKeys();
  const days = new Set<string>();
  const sessions = new Set<string>();
  for (const k of keys) {
    const parsed = parseEntryKey(k);
    if (!parsed) continue;
    days.add(parsed.local_day);
    sessions.add(parsed.session_id);
  }
  console.log(`Entries: ${keys.length}`);
  console.log(`Sessions: ${sessions.size}`);
  console.log(`Days covered: ${days.size}`);
  console.log(`Run \`fleetlens entries --day YYYY-MM-DD\` to inspect a specific day.`);
}

function printEntries(list: Entry[], json?: boolean): void {
  if (json) {
    console.log(JSON.stringify(list, null, 2));
    return;
  }
  for (const e of list) {
    console.log(`${e.session_id}  ${e.local_day}  ${e.numbers.active_min}m  ${e.project}  enr=${e.enrichment.status}`);
  }
}

function printHelp(): void {
  console.log(`fleetlens entries — inspect perception-layer Entries

Usage:
  fleetlens entries                       Summary: count of entries, sessions, days
  fleetlens entries --day YYYY-MM-DD      All entries for a given local day
  fleetlens entries --session UUID        All entries for a given session
  fleetlens entries --all                 All entries in the store

Options:
  --json          Output structured JSON instead of human-readable lines.

Examples:
  fleetlens entries
  fleetlens entries --day 2026-04-22
  fleetlens entries --day 2026-04-22 --json | jq '.[].enrichment.status'
  fleetlens entries --session abc123 --json`);
}
