// packages/cli/src/commands/entries.ts
//
// Read-only CLI command for inspecting Entries generated by the perception
// worker. Phase 1a — regeneration is daemon-driven; a `regenerate` subcommand
// is deferred to Phase 1b where it shares logic with the enrichment pipeline.

import { parseEntryKey, type Entry } from "@claude-lens/entries";
import {
  listEntriesForDay,
  listEntriesForSession,
  listEntryKeys,
  readEntry,
} from "@claude-lens/entries/fs";
import { flag } from "../args.js";

export async function entries(args: string[]): Promise<void> {
  if (args.includes("--help") || args.includes("-h")) {
    printHelp();
    return;
  }

  if (args[0] === "regenerate") {
    await regenerate(args.slice(1));
    return;
  }

  const json = args.includes("--json");
  const dayArg = flag(args, "--day");
  const sessionArg = flag(args, "--session");
  const all = args.includes("--all");

  if (dayArg) {
    printEntries(listEntriesForDay(dayArg), json);
    return;
  }
  if (sessionArg) {
    printEntries(listEntriesForSession(sessionArg), json);
    return;
  }
  if (all) {
    const list: Entry[] = [];
    for (const key of listEntryKeys()) {
      const parsed = parseEntryKey(key);
      if (!parsed) continue;
      const e = readEntry(parsed.session_id, parsed.local_day);
      if (e) list.push(e);
    }
    printEntries(list, json);
    return;
  }

  // Default: summary counts.
  const keys = listEntryKeys();
  const days = new Set<string>();
  const sessions = new Set<string>();
  for (const k of keys) {
    const parsed = parseEntryKey(k);
    if (!parsed) continue;
    days.add(parsed.local_day);
    sessions.add(parsed.session_id);
  }
  console.log(`Entries: ${keys.length}`);
  console.log(`Sessions: ${sessions.size}`);
  console.log(`Days covered: ${days.size}`);
  console.log(`Run \`fleetlens entries --day YYYY-MM-DD\` to inspect a specific day.`);
}

function printEntries(list: Entry[], json?: boolean): void {
  if (json) {
    console.log(JSON.stringify(list, null, 2));
    return;
  }
  for (const e of list) {
    console.log(`${e.session_id}  ${e.local_day}  ${e.numbers.active_min}m  ${e.project}  enr=${e.enrichment.status}`);
  }
}

async function regenerate(args: string[]): Promise<void> {
  const since = flag(args, "--since");
  const force = args.includes("--force");
  const json = args.includes("--json");

  const { readSettings, runEnrichmentQueue, monthToDateSpend } = await import("@claude-lens/entries/node");
  const { writeEntry, listEntriesWithStatus } = await import("@claude-lens/entries/fs");

  const settings = readSettings();
  if (!settings.ai_features.enabled) {
    console.error("ai_features.enabled is false — nothing to do. Toggle it in Settings or settings.json.");
    process.exit(2);
  }

  // --force: reset matched Entries to pending + retry_count=0 before running the queue.
  // Explicitly excludes skipped_trivial — triviality is deterministic, re-enriching is wasteful.
  if (force) {
    const candidates = listEntriesWithStatus(["done", "error", "pending"])
      .filter(e => !since || e.local_day >= since);
    for (const e of candidates) {
      writeEntry({
        ...e,
        enrichment: {
          ...e.enrichment,
          status: "pending",
          retry_count: 0,
          error: null,
          generated_at: null,
        },
      });
    }
    if (!json) console.log(`Reset ${candidates.length} Entries to pending.`);
  }

  const budgetBefore = monthToDateSpend();
  const result = await runEnrichmentQueue(settings.ai_features);
  const budgetAfter = monthToDateSpend();

  if ("skipped" in result && typeof result.skipped === "string") {
    if (json) console.log(JSON.stringify(result));
    else console.log(`skipped: ${result.skipped}`);
    const exit = result.skipped === "disabled" ? 2
      : result.skipped === "budget_cap_reached" ? 3
      : 0;
    process.exit(exit);
  }
  const r = result as { enriched: number; errors: number; skipped: number };
  if (json) console.log(JSON.stringify(r));
  else console.log(`enriched=${r.enriched} errors=${r.errors} skipped=${r.skipped}`);

  // Detect budget exceeded mid-run: spend advanced AND is now >= cap -> exit 3.
  const cap = settings.ai_features.monthlyBudgetUsd;
  if (cap !== null && budgetAfter > budgetBefore && budgetAfter >= cap) {
    process.exit(3);
  }
  process.exit(0);
}

function printHelp(): void {
  console.log(`fleetlens entries — inspect and regenerate perception-layer Entries

Usage:
  fleetlens entries                            Summary: count of entries, sessions, days
  fleetlens entries --day YYYY-MM-DD           All entries for a given local day
  fleetlens entries --session UUID             All entries for a given session
  fleetlens entries --all                      All entries in the store
  fleetlens entries regenerate [--since D] [--force] [--json]
                                               Re-run enrichment. --force resets
                                               status+retry_count on matched non-trivial
                                               Entries (skipped_trivial NOT reset).

Exit codes:
  0 — success (or no-op)
  2 — ai_features.enabled is false
  3 — monthly budget cap reached (pre-run or mid-run)
`);
}
