import { InsightsView } from "@/components/insights-view";

export const dynamic = "force-dynamic";

export default function InsightsPage() {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 20,
        maxWidth: 900,
        padding: "32px 40px",
      }}
    >
      <header style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, letterSpacing: "-0.02em", margin: 0 }}>
          Insights
        </h1>
        <p style={{ fontSize: 13, color: "var(--af-text-secondary)", margin: 0, lineHeight: 1.55 }}>
          Narrative retrospective generated by a local Claude subprocess. Reads behavioural
          capsules from your sessions — no transcripts or token counts, just the signals that
          matter: shipping, stuck patterns, subagent orchestration, skill adoption.
        </p>
      </header>
      <InsightsView />
    </div>
  );
}
