import { z } from "zod";
import type { DayDigest, Entry } from "../types.js";

const SuggestionSchema = z.object({
  headline: z.string().min(1).max(80),
  body: z.string().min(1).max(300),
});

export const DayDigestResponseSchema = z.object({
  headline: z.string().min(1).max(160),
  narrative: z.string().max(1200).nullable(),
  what_went_well: z.string().max(400).nullable(),
  what_hit_friction: z.string().max(400).nullable(),
  suggestion: SuggestionSchema.nullable(),
}).passthrough();

export type DayDigestResponse = z.infer<typeof DayDigestResponseSchema>;

const SYSTEM_PROMPT = `You are synthesizing a developer's Claude Code activity for a single local day into a short, honest narrative digest.

Input is:
- DAY FACTS: deterministic aggregates (agent_min, projects, shipped PRs, concurrency_peak, top_flags, top_goal_categories)
- ENTRY SUMMARIES: up to 12 per-session brief_summaries already generated by the enrichment pass
- FRICTION LINES: up to 6 entry-level friction_detail sentences (where present)
- USER INSTRUCTIONS: up to 10 load-bearing asks the user gave across the day

Output ONE JSON object with five fields:

1. headline (string, one sentence, <= 120 chars):
   Second-person. Concrete verb + concrete noun. Lead with the most characteristic work of the day.
   Good: "You shipped the Team Edition timeline after two subagent retries."
   Bad:  "You had a productive day."

2. narrative (string, 2-4 sentences, <= 600 chars, or null):
   Second-person. Weave the top 3-5 entries into a coherent arc. Name projects. Name specific wins or blockers. Do NOT list every entry.

3. what_went_well (string, ONE sentence or null):
   The strongest positive signal from the day. Tie to a concrete cause ("Subagent loop settled after you split the spec review"). Null if the day was truly friction-dominated.

4. what_hit_friction (string, ONE sentence or null):
   The most load-bearing friction. Tie to a concrete cause. Null if the day was smooth.

5. suggestion (object { headline: string <= 60 chars, body: string <= 240 chars } or null):
   One actionable next step for tomorrow, grounded in today's pattern. Null if nothing obvious suggests itself; don't pad with truisms.

CRITICAL RULES:

- Second-person ("you ..."), not third-person.
- Copy the user's phrasings where useful; do not invent features or outcomes not in the input.
- Do not mention a project unless it's in DAY FACTS.projects.
- Do not fabricate PR counts, commits, or timestamps.
- If input is sparse (<= 2 entries or <= 10 active_min), err shorter — a one-line headline + null narrative is fine.

RESPOND WITH ONLY VALID JSON (no prose, no code fence):

{
  "headline": "...",
  "narrative": "..." | null,
  "what_went_well": "..." | null,
  "what_hit_friction": "..." | null,
  "suggestion": { "headline": "...", "body": "..." } | null
}`;

export const DIGEST_DAY_SYSTEM_PROMPT = SYSTEM_PROMPT;

function trunc(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1) + "…";
}

function prettyProject(p: string): string {
  const parts = p.split("/").filter(Boolean);
  return parts[parts.length - 1] ?? p;
}

export function buildDigestUserPrompt(base: DayDigest, entries: Entry[]): string {
  const enriched = entries.filter(e => e.enrichment.status === "done");

  const summaries = enriched
    .slice(0, 12)
    .map(e => `- (${prettyProject(e.project)}, ${Math.round(e.numbers.active_min)}m) ${trunc(e.enrichment.brief_summary ?? "", 240)}`)
    .join("\n");

  const frictions = enriched
    .map(e => e.enrichment.friction_detail)
    .filter((x): x is string => !!x)
    .slice(0, 6)
    .map((f, i) => `${i + 1}. ${trunc(f, 240)}`)
    .join("\n");

  const instructions = enriched
    .flatMap(e => e.enrichment.user_instructions)
    .slice(0, 10)
    .map((s, i) => `${i + 1}. ${trunc(s, 240)}`)
    .join("\n");

  const facts = {
    date: base.key,
    agent_min: base.agent_min,
    project_count: base.projects.length,
    projects: base.projects.map(p => ({ name: p.display_name, share_pct: p.share_pct })),
    shipped_count: base.shipped.length,
    shipped_titles: base.shipped.map(s => s.title),
    concurrency_peak: base.concurrency_peak,
    top_flags: base.top_flags,
    top_goal_categories: base.top_goal_categories,
  };

  return `DAY FACTS:
${JSON.stringify(facts, null, 2)}

ENTRY SUMMARIES (up to 12, most significant first):
${summaries || "(none — no enriched entries)"}

FRICTION LINES (up to 6):
${frictions || "(none — smooth day)"}

USER INSTRUCTIONS (up to 10 load-bearing asks):
${instructions || "(none)"}`;
}
