import root from "../../eslint.config.mjs";
// Add a CLI-local ignore for the bundled standalone Next.js app — it's
// generated by scripts/prepare-cli.mjs and shouldn't be linted. The root
// config has the same ignore but its path is anchored at repo root, so it
// doesn't take effect when eslint runs from packages/cli/ as its cwd.
export default [
  { ignores: ["app/**"] },
  ...root,
];
