import {
  readDayDigest, writeWeekDigest,
  readWeekDigest,
  getCurrentWeekDigestFromCache, setCurrentWeekDigestInCache,
} from "./digest-fs.js";
import { runDayDigestPipeline, type PipelineEvent, type PipelineOptions as DayPipelineOptions } from "./digest-day-pipeline.js";
import { generateWeekDigest, buildDeterministicWeekDigest, weekDates } from "./digest-week.js";
import { appendSpend } from "./budget.js";
import { writeInteractiveLock, removeInteractiveLock } from "./pipeline-lock.js";
import type { CallLLM } from "./enrich.js";
import type { AiFeaturesSettings } from "./settings.js";
import type { DayDigest, WeekDigest } from "./types.js";

export type WeekPipelineOptions = {
  settings: AiFeaturesSettings;
  force?: boolean;
  callLLM?: CallLLM;
  now?: () => number;
  /** Current local Monday in server TZ; if `monday === currentWeekMonday`, persist to in-memory cache instead of disk. */
  currentWeekMonday: string;
  /** Current local day; sub-pipelines need this. */
  todayLocalDay: string;
  caller?: "web" | "cli" | "daemon";
};

/** Returns the Monday (in local TZ) for the given local YYYY-MM-DD. */
export function mondayFor(localDay: string): string {
  const d = new Date(`${localDay}T00:00:00`);
  const dow = d.getDay(); // 0=Sun, 1=Mon, ...
  const offset = dow === 0 ? -6 : 1 - dow;
  d.setDate(d.getDate() + offset);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export async function* runWeekDigestPipeline(
  monday: string,
  opts: WeekPipelineOptions,
): AsyncGenerator<PipelineEvent, void, void> {
  const now = opts.now ?? (() => Date.now());
  const isCurrentWeek = monday === opts.currentWeekMonday;
  const aiOn = opts.settings.enabled;

  // Short-circuit: past week, cached on disk, !force
  if (!isCurrentWeek && !opts.force) {
    const cached = readWeekDigest(monday);
    if (cached) { yield { type: "digest", digest: cached }; return; }
  }

  // Short-circuit: current week, cached in TTL, !force
  if (isCurrentWeek && !opts.force) {
    const cached = getCurrentWeekDigestFromCache(monday, now());
    if (cached) { yield { type: "digest", digest: cached }; return; }
  }

  // Stage 0: collect day digests for the 7 dates of the week.
  // Past-day digests get auto-generated inline if missing. Today's digest
  // is read from cache only — never force-generated by a week-pipeline trigger.
  yield { type: "status", phase: "load_dependencies", text: `Loading 7 days for week of ${monday}` };
  const dates = weekDates(monday);
  const dayDigests: DayDigest[] = [];

  for (const date of dates) {
    const isFuture = date > opts.todayLocalDay;
    if (isFuture) {
      yield { type: "dependency", kind: "day", key: date, status: "cached" };
      continue;
    }
    const isToday = date === opts.todayLocalDay;

    const cached = isToday ? null : readDayDigest(date);
    if (cached) {
      dayDigests.push(cached);
      yield { type: "dependency", kind: "day", key: date, status: "cached" };
      continue;
    }

    if (isToday) {
      // Read today via the day pipeline (TTL-cached short-circuit). Never force.
      const subOpts: DayPipelineOptions = {
        settings: opts.settings, force: false, callLLM: opts.callLLM, now: opts.now,
        todayLocalDay: opts.todayLocalDay, caller: opts.caller,
      };
      let captured: DayDigest | null = null;
      let failed = false;
      for await (const ev of runDayDigestPipeline(date, subOpts)) {
        if (ev.type === "digest" && ev.digest.scope === "day") captured = ev.digest as DayDigest;
        if (ev.type === "error") { failed = true; break; }
      }
      if (captured) {
        dayDigests.push(captured);
        yield { type: "dependency", kind: "day", key: date, status: "cached" };
      } else if (failed) {
        yield { type: "dependency", kind: "day", key: date, status: "failed" };
      }
      continue;
    }

    // Past day, no cache → generate inline via the day pipeline.
    const subOpts: DayPipelineOptions = {
      settings: opts.settings, force: false, callLLM: opts.callLLM, now: opts.now,
      todayLocalDay: opts.todayLocalDay, caller: opts.caller,
    };
    let captured: DayDigest | null = null;
    let failed = false;
    for await (const ev of runDayDigestPipeline(date, subOpts)) {
      // Forward the sub-pipeline's entry/progress events so the SSE client
      // sees enrichment ticking, but suppress sub-digest "digest" events
      // (we'll emit our own week digest at the end). Suppress "saved" too —
      // the user is generating a week, not a day.
      if (ev.type === "digest") {
        if (ev.digest.scope === "day") captured = ev.digest as DayDigest;
        continue;
      }
      if (ev.type === "saved") continue;
      if (ev.type === "error") { failed = true; continue; }
      yield ev;
    }
    if (captured) {
      dayDigests.push(captured);
      yield { type: "dependency", kind: "day", key: date, status: "generated" };
    } else if (failed) {
      yield { type: "dependency", kind: "day", key: date, status: "failed" };
    }
  }

  if (dayDigests.length === 0) {
    yield { type: "error", message: `no day digests available for week of ${monday}` };
    return;
  }

  if (aiOn) writeInteractiveLock();
  try {
    let digest: WeekDigest;
    if (aiOn) {
      yield { type: "status", phase: "synth", text: "Synthesizing week narrative" };
      const progressQueue: Array<{ bytes: number; elapsed_ms: number }> = [];
      const synthPromise = generateWeekDigest(monday, dayDigests, {
        model: opts.settings.model, callLLM: opts.callLLM,
        onProgress: info => { progressQueue.push({ bytes: info.bytes, elapsed_ms: info.elapsedMs }); },
      });

      let done = false;
      synthPromise.finally(() => { done = true; });
      while (!done) {
        await new Promise(r => setTimeout(r, 500));
        if (progressQueue.length > 0) {
          const latest = progressQueue[progressQueue.length - 1]!;
          yield { type: "progress", phase: "synth", bytes: latest.bytes, elapsed_ms: latest.elapsed_ms };
          progressQueue.length = 0;
        }
      }
      const r = await synthPromise;
      digest = r.digest;
      if (r.usage) {
        appendSpend({
          ts: new Date().toISOString(), caller: opts.caller ?? "web",
          model: digest.model ?? opts.settings.model,
          input_tokens: r.usage.input_tokens,
          output_tokens: r.usage.output_tokens,
          cost_usd: digest.cost_usd ?? 0,
          kind: "week_digest", ref: monday,
        });
      }
    } else {
      digest = buildDeterministicWeekDigest(monday, dayDigests);
    }

    if (!isCurrentWeek) {
      writeWeekDigest(digest);
      yield { type: "saved", path: `~/.cclens/digests/week/${monday}.json` };
    } else {
      digest.is_live = true;
      setCurrentWeekDigestInCache(monday, digest, now());
    }

    yield { type: "digest", digest };
  } finally {
    if (aiOn) removeInteractiveLock();
  }
}
